ors.token=<yourtokenpleasepasthere>
ors.matrix.url=http://api.openrouteservice.org/v2/matrix/driving-car
ors.geocode.url=http://api.openrouteservice.org/geocode/search
emission.co2.factors=diesel-car-small=0.142,petrol-car-small=0.153,plugin-hybrid-car-small=0.105,electric-car-small=0.049,diesel-car-medium=0.170,petrol-car-medium=0.192,plugin-hybrid-car-medium=0.109,electric-car-medium=0.057,diesel-car-large=0.209,petrol-car-large=0.282,plugin-hybrid-car-large=0.125,electric-car-large=0.073,bus-default=0.027,train-default=0.006
